# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objectDetectionService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cobjectDetectionService.proto\x12\x16objectDetectionService"#\n\rImageProvided\x12\x12\n\nimageBytes\x18\x01 \x01(\x0c":\n\tDetection\x12\x18\n\x10imageEditedBytes\x18\x01 \x01(\x0c\x12\x13\n\x0bobjectIndex\x18\x02 \x01(\x05\x32j\n\x0eObjectDetector\x12X\n\x0c\x64\x65tectObject\x12%.objectDetectionService.ImageProvided\x1a!.objectDetectionService.Detectionb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "objectDetectionService_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _IMAGEPROVIDED._serialized_start = 56
    _IMAGEPROVIDED._serialized_end = 91
    _DETECTION._serialized_start = 93
    _DETECTION._serialized_end = 151
    _OBJECTDETECTOR._serialized_start = 153
    _OBJECTDETECTOR._serialized_end = 259
# @@protoc_insertion_point(module_scope)
