# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import autoReplyService_pb2 as autoReplyService__pb2


class QuestionReplyerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.replyQuestion = channel.unary_unary(
                '/autoReplyService.QuestionReplyer/replyQuestion',
                request_serializer=autoReplyService__pb2.Question.SerializeToString,
                response_deserializer=autoReplyService__pb2.Reply.FromString,
                )


class QuestionReplyerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def replyQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuestionReplyerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'replyQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.replyQuestion,
                    request_deserializer=autoReplyService__pb2.Question.FromString,
                    response_serializer=autoReplyService__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoReplyService.QuestionReplyer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QuestionReplyer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def replyQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/autoReplyService.QuestionReplyer/replyQuestion',
            autoReplyService__pb2.Question.SerializeToString,
            autoReplyService__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
