# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autoReplyService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61utoReplyService.proto\x12\x10\x61utoReplyService\"7\n\x08Question\x12\x17\n\x0fquestionMessage\x18\x01 \x01(\t\x12\x12\n\nuserApiKey\x18\x02 \x01(\t\"\x1d\n\x05Reply\x12\x14\n\x0creplyMessage\x18\x01 \x01(\t2W\n\x0fQuestionReplyer\x12\x44\n\rreplyQuestion\x12\x1a.autoReplyService.Question\x1a\x17.autoReplyService.Replyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autoReplyService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUESTION._serialized_start=44
  _QUESTION._serialized_end=99
  _REPLY._serialized_start=101
  _REPLY._serialized_end=130
  _QUESTIONREPLYER._serialized_start=132
  _QUESTIONREPLYER._serialized_end=219
# @@protoc_insertion_point(module_scope)
